This changeset will allow an oms DSC package to be built if the user specifies "--oms" at the configure line.  This also refactors some of the OMI_HOME environment variables so they're set during configure time, instead of runtime.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,57 +6,75 @@ BUILD_SSL_098=1
 BUILD_SSL_100=1
 BUILD_SSL_SYSTEM=0
 BUILD_DEBUG=0
+BUILD_OMS=
 DEBUG_FLAGS=""
+DSC_MODULES_PATH="/opt/microsoft/dsc/modules"
+DSC_SCRIPT_PATH="/opt/microsoft/dsc/Scripts"
 
 for opt
 do
-
-  arg=`expr "x$opt" : 'x[^=]*=\(.*\)'`
-
-  case $opt in
-    -h | --help)
-      help=1
-    ;;
-    --enable-debug)
-      if [ "$build_type" = "Bullseye" ]; then
-          echo "Cannot build debug if Bullseye is enabled"
-          exit 1
-      fi
-      BUILD_DEBUG=1
-      DEBUG_FLAGS="--enable-debug"
-    ;;
-
-
-    --no-rpm)
-      BUILD_RPM=0
-    ;;
-    --no-dpkg)
-      BUILD_DPKG=0
-    ;;
-
-    --local)
-      BUILD_LOCAL=1
-    ;;
-
-    --no-ssl-098)
-      BUILD_SSL_098=0
-    ;;
-    --no-ssl-100)
-      BUILD_SSL_100=0
-    ;;
-
-    *)
-      echo "configure: invalid option '$opt'"
-      echo "Try configure --help' for more information."
-      exit 1
-    ;;
-
-  esac
-
+    
+    arg=`expr "x$opt" : 'x[^=]*=\(.*\)'`
+    
+    case $opt in
+	-h | --help)
+	    help=1
+	    ;;
+	--enable-debug)
+	    if [ "$build_type" = "Bullseye" ]; then
+		echo "Cannot build debug if Bullseye is enabled"
+		exit 1
+	    fi
+	    BUILD_DEBUG=1
+	    DEBUG_FLAGS="--enable-debug"
+	    ;;
+	
+	
+	--no-rpm)
+	    BUILD_RPM=0
+	    ;;
+	--no-dpkg)
+	    BUILD_DPKG=0
+	    ;;
+	
+	--local)
+	    if [ "$BUILD_OMS" = "BUILD_OMS" ]; then
+		echo "Error: options --oms and --local conflict."
+		exit 1
+	    fi
+	    BUILD_LOCAL=1
+	    DSC_MODULES_PATH="\$(CONFIG_DATADIR)/dsc/modules"
+	    DSC_SCRIPT_PATH="\$(CONFIG_DATADIR)/dsc/Scripts"
+	    ;;
+	
+	--no-ssl-098)
+	    BUILD_SSL_098=0
+	    ;;
+	--no-ssl-100)
+	    BUILD_SSL_100=0
+	    ;;
+	--oms)
+	    if [ "$BUILD_LOCAL" = "1" ]; then
+		echo "Error: options --oms and --local conflict."
+		exit 1
+	    fi
+	    BUILD_OMS=BUILD_OMS
+	    DSC_MODULES_PATH="/opt/microsoft/omsconfig/modules"
+	    DSC_SCRIPT_PATH="/opt/microsoft/omsconfig/Scripts"
+	    ;;
+	
+	*)
+	    echo "configure: invalid option '$opt'"
+	    echo "Try configure --help' for more information."
+	    exit 1
+	    ;;
+	
+    esac
+    
 done
 
 if [ "$help" = "1" ]; then
-
+    
     cat<<EOF
 
 Usage: ./configure [OPTIONS]
@@ -88,7 +106,7 @@ if [ -d "/usr/local_ssl_0.9.8" -a -d "/usr/local_ssl_1.0.0" ]; then
             openssl098_libdir=/usr/local_ssl_0.9.8/lib
             openssl100_libdir=/usr/local_ssl_1.0.0/lib64
             ;;
-
+	
         * )
             openssl098_libdir=/usr/local_ssl_0.9.8/lib
             openssl100_libdir=/usr/local_ssl_1.0.0/lib
@@ -106,6 +124,9 @@ BUILD_DPKG=$BUILD_DPKG
 BUILD_SSL_098=$BUILD_SSL_098
 BUILD_SSL_100=$BUILD_SSL_100
 BUILD_LOCAL=$BUILD_LOCAL
+BUILD_OMS=$BUILD_OMS
+DSC_MODULES_PATH=$DSC_MODULES_PATH
+DSC_SCRIPT_PATH=$DSC_SCRIPT_PATH
 
 BUILD_DEBUG=$BUILD_DEBUG
 DEBUG_FLAGS=$DEBUG_FLAGS
